stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/iris.csv
    outs:
      - data/processed/iris_processed.csv

  featureize:
    cmd: python src/featureize.py
    deps:
      - src/featureize.py
      - data/processed/iris_processed.csv
    outs:
      - data/featureized/iris_featureized.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/featureized/iris_featureized.csv
    outs:
      - models/iris_model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/iris_model.pkl
      - data/featureized/iris_featureized.csv
