stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/iris.csv
    outs:
      - data/processed/iris_processed.csv
    params:
      - prepare.data_path
      - prepare.output_path

  featureize:
    cmd: python src/featureize.py
    deps:
      - src/featureize.py
      - data/processed/iris_processed.csv
    outs:
      - data/featureized/iris_featureized.csv
    params:
      - featureize.input_path
      - featureize.output_path

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/featureized/iris_featureized.csv
    outs:
      - models/iris_model.pkl
      - run_id.yaml  # This file will contain the run_id
    params:
      - train.input_path
      - train.model_output
      - train.test_size
      - train.random_state
      - train.max_depth
      - train.n_estimators

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/iris_model.pkl
      - data/featureized/iris_featureized.csv
    params:
      - evaluate.model_path
      - evaluate.test_data_path

  register:
    cmd: python src/register_model.py
    deps:
      - src/register_model.py
      - models/iris_model.pkl
      - run_id.yaml  
    params:
      - register.model_name
      - register.staging_stage
      - register.production_stage
