apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml-app
  labels:
    app: fastapi-ml-app
spec:
  replicas: 2  # Number of replicas for scaling
  selector:
    matchLabels:
      app: fastapi-ml-app
  template:
    metadata:
      labels:
        app: fastapi-ml-app
    spec:
      containers:
      - name: fastapi-ml-app
        image: mlops.azurecr.io/fastapi-ml-app:latest
        ports:
        - containerPort: 8000  # Expose container's port 8000
          protocol: TCP  # Explicitly specifying the protocol
        readinessProbe:  # Ensure the pod is ready to receive traffic
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3  # Wait time before the first check
          periodSeconds: 5  # Check readiness every 5 seconds
        livenessProbe:  # Ensure the pod is running correctly
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10  # Wait time before the first check
          periodSeconds: 10  # Check liveness every 10 seconds
  strategy:
    type: RollingUpdate  # Rolling update strategy for zero-downtime deployment
    rollingUpdate:
      maxSurge: 1  # Allow 1 extra pod to be created during update
      maxUnavailable: 0  # Ensure no pods are unavailable during update
